"""empty message

Revision ID: 52bdb6232889
Revises: 65348b3862b7
Create Date: 2022-05-23 14:24:57.376280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bdb6232889'
down_revision = '65348b3862b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weapon', 'weapon_description',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weapon', 'weapon_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=800),
               existing_nullable=False)
    # ### end Alembic commands ###
