"""empty message

Revision ID: 84d102b06500
Revises: e9309567269e
Create Date: 2022-05-20 16:14:29.148477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d102b06500'
down_revision = 'e9309567269e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signet_name', sa.String(length=120), nullable=False),
    sa.Column('signet_image', sa.String(length=120), nullable=False),
    sa.Column('signet_description', sa.String(length=80), nullable=False),
    sa.Column('best_used', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signet_image')
    )
    op.drop_table('sigils')
    op.add_column('character', sa.Column('best_signets', sa.String(length=80), nullable=False))
    op.drop_column('character', 'best_sigils')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('best_sigils', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('character', 'best_signets')
    op.create_table('sigils',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sigil_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sigil_image', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sigil_description', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('best_used', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sigils_pkey'),
    sa.UniqueConstraint('sigil_image', name='sigils_sigil_image_key')
    )
    op.drop_table('signets')
    # ### end Alembic commands ###
