"""empty message

Revision ID: e9309567269e
Revises: e85cae2e744d
Create Date: 2022-05-19 18:41:54.090402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9309567269e'
down_revision = 'e85cae2e744d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'image',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'image',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
