"""empty message

Revision ID: f05274cd6b7d
Revises: 
Create Date: 2022-05-25 15:34:18.814843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05274cd6b7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=800), nullable=False),
    sa.Column('image', sa.String(length=800), nullable=False),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('best_signets', sa.String(length=800), nullable=False),
    sa.Column('best_weapon', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signet_name', sa.String(length=800), nullable=False),
    sa.Column('signet_image', sa.String(length=800), nullable=False),
    sa.Column('signet_description', sa.String(length=800), nullable=False),
    sa.Column('best_used', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signet_image')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=800), nullable=False),
    sa.Column('weapon_image', sa.String(length=800), nullable=False),
    sa.Column('weapon_description', sa.Text(), nullable=False),
    sa.Column('abilities', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weapon_image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    op.drop_table('user')
    op.drop_table('signets')
    op.drop_table('character')
    # ### end Alembic commands ###
